void DriveForward(int time)
{
  'motor'[leftServo] = 15;
  'motor'[rightServo] = 15;
  wait1Msec(time);
}
void TurnLeft()
{
  'motor'[leftServo] = -15;
  'motor'[rightServo] = 15;
  wait1Msec(470);  
}
void TurnRight()
{

 'motor'[leftServo] = 15; 
  wait1Msec(460);  
}
void Stop()
{
 pragma config(CircuitBoardType, typeCktBoardUNO)
#pragma config(PluginCircuitBoard, typeShieldParallaxBoeBot)
#pragma config(UART_Usage, UART0, uartSystemCommPort, baudRate200000, IOPins, dgtl1, dgtl0)
#pragma config(Motor,  servo_10,        leftServo,     tmotorServoContinuousRotation, openLoop, IOPins, dgtl10, None)
#pragma config(Motor,  servo_11,        rightServo,    tmotorServoContinuousRotation, openLoop, reversed, IOPins, dgtl11, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
 
task main()
{
  wait1Msec(1000);         //pause code execution for 1000ms (1 second)
 
  motor[leftServo] = -15;
  motor[rightServo] = 15;
  wait1Msec(500);
  motor[leftServo] = 0;
  motor[rightServo] = 0;
}
}
wait1Msec(1000);
 
  DriveForward(2207);  
  TurnLeft();
  DriveForward(3862);  
  TurnRight();
  DriveForward(2207);  
  TurnRight();
  DriveForward(2207);  
  Stop();
}
